// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpTtypbSHN9Y4Ux9CxC0FnkOS5-qbqjJo',
    appId: '1:715441100211:web:59a9d2cc07cb8b3a69a7c6',
    messagingSenderId: '715441100211',
    projectId: 'kasipayz',
    authDomain: 'kasipayz.firebaseapp.com',
    storageBucket: 'kasipayz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKupogogzW93NCsHH8bbMCuKZ7vTDe3PU',
    appId: '1:715441100211:android:b44624fa0fef4e2469a7c6',
    messagingSenderId: '715441100211',
    projectId: 'kasipayz',
    storageBucket: 'kasipayz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGl3KhGrQzrfQNZdkk-h8cEdaGeAl0XR0',
    appId: '1:715441100211:ios:96694ca9d069c3e869a7c6',
    messagingSenderId: '715441100211',
    projectId: 'kasipayz',
    storageBucket: 'kasipayz.firebasestorage.app',
    iosBundleId: 'com.example.kasipayz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGl3KhGrQzrfQNZdkk-h8cEdaGeAl0XR0',
    appId: '1:715441100211:ios:96694ca9d069c3e869a7c6',
    messagingSenderId: '715441100211',
    projectId: 'kasipayz',
    storageBucket: 'kasipayz.firebasestorage.app',
    iosBundleId: 'com.example.kasipayz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpTtypbSHN9Y4Ux9CxC0FnkOS5-qbqjJo',
    appId: '1:715441100211:web:b16c06626086e8f569a7c6',
    messagingSenderId: '715441100211',
    projectId: 'kasipayz',
    authDomain: 'kasipayz.firebaseapp.com',
    storageBucket: 'kasipayz.firebasestorage.app',
  );
}
